In [ ]:
import torch
import numpy as np

In [ ]:
print(torch.__version__)

2.1.0+cu121


In [ ]:
torch.backends.mps.is_available()

False

In [ ]:
torch.cuda.is_available()

False

# Tensor



In [ ]:
dd = np.array([[1,2,3],
      [4,5,6],
      [7,8,9]])

print(dd[0][2])
print(dd[0,2])

3
3


## rank, axis, shape

**rank n** tenser: a tensor require n indices to access element, or how many axies a tensor have (not the rank in math)

an **axis** of tensor is a specific dimension of tensor

length of each axis tells us how much indices are available along each axis

The **shape/size** of tensor is determined by length of each axis

The rank of a variable is the same as the length of shape



## Reshaping tensor

In [ ]:
t = torch.tensor(dd)
t.shape

torch.Size([3, 3])

In [ ]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
print(t.dtype)
print(t.device)
print(t.layout)
# layout tell us how is our data is layout in memory

torch.int64
cpu
torch.strided


## Creating tensor from data

In [ ]:
t = np.array([1,2,3])
type(t)

numpy.ndarray

In [ ]:
t1 = torch.Tensor(t)
t2 = torch.tensor(t)
t3 = torch.as_tensor(t)
t4 = torch.from_numpy(t)

t1 return floats, but the other three seemmingly the same

In [ ]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int64
torch.int64
torch.int64


In [ ]:
torch.get_default_dtype()

torch.float32

the other three will infer the data type from the input since they are factory function

In [ ]:
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3])

In [ ]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
torch.tensor(np.array([1,2,3]),dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

## Operations

In [ ]:
print(torch.eye(2))
print(torch.ones(2,2))
print(torch.zeros(2,2))
print(torch.rand(2,2))

tensor([[1., 0.],
        [0., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0.3820, 0.0061],
        [0.5667, 0.9079]])


## Sharing vs Copying

In [ ]:
data = np.array([1,2,3])

In [ ]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [ ]:
# change the value of data but not the tensor
data[0] = 0
data[1] = 0
data[2] = 0

In [ ]:
# this two create additional copy of input data in memory
print(t1)
print(t2)
# this two share input data in memory
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([0, 0, 0])
tensor([0, 0, 0])


The **best copy function** is "*torch.tensor*" since it is factory function (so it infer data type from input data), while torch.Tensor is not (it use default data type).


The **best sharing function** is "*torch.as_tensor*" since it takes any python data type as input, while torch.from_numpy only takes numpy variable.



    1.由于numpy.ndaaray对象分配在CPU上，所以如果使用GPU的话，torch.as_tensor函数必须把数据从CPU上拷到GPU上
    2.as_tensor()对于python内置的数据结构，如列表，是无效的
    3.as_tensor的调用要求熟悉共享特征，以免对底层数据做不必要的更改，而影响到对象
    4.当as_tensor和numpy.ndarray有大量的相互往返的操作时，对性能的提升会有较大的影响


In [ ]:
lsit = [1,2,3]

In [ ]:
list_tensor = torch.as_tensor(lsit)
print(list_tensor)

tensor([1, 2, 3])


In [ ]:
lsit[0] = 0
lsit[1] = 0
lsit[2] = 0

In [ ]:
print(list_tensor)

tensor([1, 2, 3])


# Tensor operation types


    Reshaping operations
    Element-wise operations
    Reduction operations
    Access operations


## Reshaping

In [ ]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
],dtype = torch.float32)

In [ ]:
t.size()

torch.Size([3, 4])

In [ ]:
t.shape

torch.Size([3, 4])

In [ ]:
# the rank
len(t.shape)

2

In [ ]:
torch.tensor(t.shape).prod()

tensor(12)

In [ ]:
# numel: number of elelment
t.numel()

12

In [ ]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [ ]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [ ]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [ ]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [ ]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [ ]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [ ]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [ ]:
t.reshape(4,1,3)

tensor([[[1., 1., 1.]],

        [[1., 2., 2.]],

        [[2., 2., 3.]],

        [[3., 3., 3.]]])

In [ ]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


squeeze() remove all the axis that has length 1

In [ ]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


unsqueeze() add a dimension with a length of 1

In [ ]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


### flatten

In [ ]:
def flatten(x):
  # -1 tells the reshape function to figure out what the value should be
  x = x.reshape(1,-1)
  x = x.squeeze()
  return x

In [ ]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [ ]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [ ]:
t.reshape(1,12).squeeze()

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [ ]:
t.reshape(1,-1)[0]

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [ ]:
t.reshape(-1)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

### concatenating

In [ ]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])

Combine two tensor row-wise axis = 0

In [ ]:
torch.cat((t1, t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

Comnine two tensor col-wise axis = 1

In [ ]:
torch.cat((t1, t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

### flatten operation visualization

In [ ]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

concatenate three tensor along a new axis

In [ ]:
t = torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 4, 4])

the first axis represent the number of batch
the second and the third represent the height and width of single batch

In [ ]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [ ]:
t = t.reshape(3,1,4,4)

In [ ]:
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])



*   each element in the first axis represent a image
*   for each image, there's a single color channel
*   in each channel it containg a 4 by 4 array



In [ ]:
t[0] # first image

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [ ]:
t[0][0] # first color channel in the first image

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [ ]:
t[0][0][0] # first row of pixel in first color channel in the first image

tensor([1, 1, 1, 1])

In [ ]:
t[0][0][0][0] # first pixel in that first row

tensor(1)

flatten the entire tensor

In [ ]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
t.flatten().shape

torch.Size([48])

flatten the image tensor (element in the first axis) in the entire tensor

In [ ]:
t.flatten(start_dim = 1).shape

torch.Size([3, 16])

In [ ]:
t.flatten(start_dim = 1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
t.reshape(3,16)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
t.reshape(3,-1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

## element wise

two tensor must have the same shape

In [ ]:
t1 = torch.tensor([
    [1,2],
    [3,4]
],dtype = torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
],dtype = torch.float32)

In [ ]:
t1[0][0]

tensor(1.)

In [ ]:
t2[0][0]

tensor(9.)

### Addition/subtract/mult/divi

In [ ]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [ ]:
t1-t2

tensor([[-8., -6.],
        [-4., -2.]])

In [ ]:
t1*t2

tensor([[ 9., 16.],
        [21., 24.]])

In [ ]:
t1/t2

tensor([[0.1111, 0.2500],
        [0.4286, 0.6667]])

In [ ]:
t1+2

tensor([[3., 4.],
        [5., 6.]])

In [ ]:
t1-2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [ ]:
t1*2

tensor([[2., 4.],
        [6., 8.]])

In [ ]:
t1/2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

but 2 is zero shape tensor, NOT THE SHAME SHAPE AS t1 !!!!!!!!

### tensor broadcasting

how tensor with different shape are treated in elelment wise operation

e.g. for above examples, 2 is bradcast to the shape of t1 and then operating elemenwise addition

In [ ]:
np.broadcast_to(2,t1.shape)

array([[2, 2],
       [2, 2]])

In [ ]:
t1 + torch.tensor(np.broadcast_to(2,t1.shape),dtype = torch.float32)

tensor([[3., 4.],
        [5., 6.]])

In [ ]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

another example

In [ ]:
t1 = torch.tensor([
    [1,1],
    [1,1]
],dtype = torch.float32)

t2 = torch.tensor([2,4],dtype = torch.float32)

In [ ]:
t1.shape

torch.Size([2, 2])

In [ ]:
t2.shape

torch.Size([2])

In [ ]:
np.broadcast_to(t2.numpy(),t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [ ]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

In [ ]:
torch.tensor([[1, 2, 3]]) + torch.tensor([[4],[5],[6]])

tensor([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]])

### Comparison

In [ ]:
t = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
],dtype = torch.float32)

In [ ]:
t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [ ]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
t.gt(0)

tensor([[False,  True,  True],
        [ True, False,  True],
        [False,  True, False]])

In [ ]:
t.lt(0)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [ ]:
t.le(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [ ]:
t.le(t)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### element wise functions

In [ ]:
t.abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [ ]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [ ]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [ ]:
t.neg().abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

### Reduction

reduce the number of element contained in the tensor

In [ ]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
],dtype = torch.float32)

In [ ]:
t.sum()

tensor(8.)

In [ ]:
t.numel()

9

In [ ]:
t.sum().numel()

1

In [ ]:
t.sum().numel()<t.numel()

True

The sum operatoin is a reduciton opereation

In [ ]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
],dtype = torch.float32)

sum along the first axis

In [ ]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

sum along the second axis

In [ ]:
t.sum(dim = 1)

tensor([ 4.,  8., 12.])

argmax

In [ ]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
],dtype = torch.float32)

In [ ]:
t.max()

tensor(5.)

In [ ]:
t.argmax()

tensor(11)

returns the index of maximum value in the flatten tensor

In [ ]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [ ]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [ ]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [ ]:
t.max(dim = 1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [ ]:
t.argmax(dim=1)

tensor([3, 1, 3])

In [ ]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
],dtype = torch.float32)

In [ ]:
t.mean()

tensor(5.)

In [ ]:
t.mean().item()

5.0

item() only applies to scalar value tensor

In [ ]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [ ]:
t.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)